---
- name: Ensure /etc/resolv.conf file is configured correctly
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - {regexp: "^search", line: "search tread-tech33.com"}
    - {regexp: "^nameserver", line: "nameserver 192.168.1.87"}

- name: Copy /etc/hosts to server
  ansible.builtin.copy:
    src: /etc/hosts
    dest: /etc/hosts

- name: Ensure hostname is set correctly
  ansible.builtin.hostname:
    name: "{{ ansible_hostname }}.{{ ipa_domain }}"

- name: Install IPA client packages
  ansible.builtin.dnf:
    name: ipa-client
    state: present

- name: Run IPA client install
  ansible.builtin.command: >
    ipa-client-install --unattended
    --domain={{ ipa_domain }}
    --realm={{ ipa_realm }}
    --server={{ ipa_server }}
    --mkhomedir
    --principal={{ ipa_admin_user }}
    --password={{ ipa_admin_password }}
  register: ipa_client_result
  changed_when: "'Enrolled in IPA realm' in ipa_client_result.stdout"

- name: Show enrollment result
  ansible.builtin.debug:
    var: ipa_client_result.stdout

